# -*- coding: utf-8 -*-
"""Eclat association Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TpZIIoszmgyb55Zbo-IVJh6-4uCXq9hp
"""

!pip install apyori

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv("/content/Market_Basket_Optimisation.csv")
transactions=[]
for i in range(0,7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0,20)])

from apyori import apriori
rules=apriori(transactions=transactions,min_support=0.003, min_confidence=0.2, min_lift=3,min_length=2, max_length=2)

results=list(rules)

results

def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    return list(zip(lhs, rhs, supports))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Product 1', 'Product 2', 'Support'])